//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean MainButton
        {
            get
            {
                return SteamVR_Actions.default_MainButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean Modifier
        {
            get
            {
                return SteamVR_Actions.default_Modifier;
            }
        }
        
        public virtual SteamVR_Action_Boolean Canceller
        {
            get
            {
                return SteamVR_Actions.default_Canceller;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Stick
        {
            get
            {
                return SteamVR_Actions.default_Stick;
            }
        }
    }
}
